# $     $     $
# CloudPayments
# $     $     $
# ======
# Помощник в монетизации Вашего проекта
# Вопросы по плагину/ошибки/опечатки? - @CloudDonate_support (Telegram)
# Приятного использования!
# ======
# Команды:
#   /cloudpayments - админ команды
#   /cart - открыть корзину
# Права:
#   cloudpayments.command.cloudpayments - доступ к /cloudpayments
#   cloudpayments.command.cart - доступ к /cart
# ======
# Не трогайте этот параметр! Он нужен для корректных обновлений
configVersion: 2

# Основные настройки
settings:
  # Включен ли режим отладки? В консоль будут выводиться отладочные сообщения
  debugMode: false
  # Период отправки запросов на получение купленных товаров в секундах.
  # Если не разбираетесь, то лучше не трогайте! Минимальное значение - 20.
  requestDelay: 20
  # Отправлять ли информацию об ошибках разработчику?
  # Лучше оставьте true, чтобы мы могли исправлять все проблемы как можно быстрее
  enableMetrics: true
  # Данные от магазина
  shop:
    shopId: "YOUR-SHOP-ID-HERE"
    shopKey: "YOUR-SHOP-KEY-HERE"
    serverId: "YOUR-SERVER-ID-HERE"

# Система сохранения операций
logs:
  # Настройки сохранения платежей
  payments:
    enabled: true
    # Формат сообщения, который будет добавляться в txt файл
    format: "{date}: {playerName} - {product} [кол-во: {amount}] (+{price} рублей). ID платежа: {paymentId}"

# Система оповещения о новых покупках в мессенджерах
messengers:
  # Настройки мессенджера Telegram
  telegram:
    enabled: false
    # Токен вашего бота
    apiToken: "YOUR-TOKEN-HERE"
    # Телеграм айди администраторов, которым будут приходить сообщения о покупках
    ids:
      - '1'
      - '2'

# Система оповещения о покупках
# Список доступных действий:
#   CHAT:сообщение - отправить сообщение от имени игрока в чат. Например: CHAT:Я крутой. Я купил товар на сайте.
#   MESSAGE:сообщение - отправить сообщение игроку в чат. Например: MESSAGE:Спасибо за покупку
#   TITLE:заголовок;подзаголовок - отправить сообщение посередине экрана игроку. Например: TITLE:Спасибо;За покупку
#   ACTIONBAR:сообщение - отправить сообщение игроку над инвентарём. Например: ACTIONBAR:Воу, поздравляем с покупкой
#   SOUND:звук;громкость;распространение - проиграть звук игроку. Например: SOUND:BLOCK_NOTE_BLOCK_BIT;1.0;1.0
#   BROADCAST:сообщение - отправить сообщение всем игрокам сервера. Например: BROADCAST:Был куплен товар
#   BROADCAST_TITLE:заголовок;подзаголовок - отправить сообщение посередине экрана всем игрокам сервера. Например: BROADCAST_TITLE:Был куплен;товар
#   BROADCAST_ACTIONBAR:сообщение - отправить сообщение над инвентарём всем игрокам сервера. Например: BROADCAST_ACTIONBAR:Был куплен товар
#   BROADCAST_SOUND:звук;громкость;распространение - проиграть звук всем игрокам сервера. Например: BROADCAST_SOUND:BLOCK_NOTE_BLOCK_BIT;1.0;1.0
#   COMMAND:команда - выполнить команду от имени игрока. Например: COMMAND:gm 1
#   CONSOLE:команда - выполнить команду от имени консоли. Например: CONSOLE:example command
# В каждом действии можно использовать заполнители. Вот их список:
#   {playerName} - Ник покупателя
#   {price} - Сумма, с учётом комиссии сервиса, которая пришла магазину
#   {product} - Название товара
#   {amount} - Количество купленного товара
inGameAnnouncements:
  # Название товара (точь-в-точь с сайта)
  'Алмаз':
    # Действия, которые будут происходить при покупке этого товара.
    actions:
      - 'MESSAGE:&9Авто&bДонат &8— &fИгрок &7{playerName}&f приобрёл &b&lАлмаз'
      - 'MESSAGE:&9Авто&bДонат &8— &fХочешь так-же? Купи донат на сайте:&b cdonate.ru'
